FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

# Install Apache + PHP + required extensions
RUN apt-get update && \
    apt-get install -y \
        apache2 \
        php \
        php-cli \
        php-mbstring \
        php-xml \
        php-intl \
        php-curl \
        unzip \
        curl \
        git \
        libicu-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Composer only (no composer install)
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Apache config
RUN a2enmod rewrite && echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN sed -i 's|DocumentRoot /var/www/html|DocumentRoot /var/www/html/public|g' /etc/apache2/sites-available/000-default.conf
RUN sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

# Set working directory
WORKDIR /var/www/html

# Copy project
COPY ./ /var/www/html

# Fix writable permissions
RUN chown -R www-data:www-data /var/www/html/writable && chmod -R 775 /var/www/html/writable

EXPOSE 80

CMD ["apache2ctl", "-D", "FOREGROUND"]
