# Use latest Ubuntu as base
FROM ubuntu:latest

# Install PHP, required extensions, and other tools
RUN apt-get update && apt-get install -y php-cli php-mbstring php-xml php-intl unzip curl git apache2 libicu-dev

RUN echo 'ServerName localhost' >> /etc/apache2/apache2.conf

# Set working directory inside container
WORKDIR /home/ubuntu

# Copy application code from host to container
# Make sure to replace './hotel-aggregator' with your actual host path
COPY ./ /home/ubuntu

CMD ['service', 'apache2', 'start']
